### ISSUE TITLE
Localization in PT-BR

### ISSUE THREAD

**Issue by JorgeALeitao** [OfficeDev/microsoft-teams-apps-speaker-queue#5]
Please discuss the possibility to release localized versions in PT-BR

**Comment by cristianoag** [comment]
App updated to support 44 different languages: en-US, eu-ES, bg-BG,ca-ES,zh-CN,zh-TW,hr-HR,cs-CZ,da-DK,nl-NL,et-EE,fi-FI,fr-FR,gl-ES,de-DE,el-GR,hi-IN,hu-HU,id-ID,it-IT,ja-JP,kk-KZ,ko-KR,lv-LV,lt-LT,ms-MY,nb-NO,pl-PL,pt-BR,pt-PT,ro-RO,ru-RU,sr-Cyrl-RS,sr-Latn-RS,sk-SK,sl-SI,es-ES,sv-SE,th-TH,tr-TR,uk-UA,vi-VN,he-IL, and ar-SA.
