### ISSUE TITLE
App doesnt exist or you do not have access

### ISSUE THREAD

**Issue by bharathidineshz** [OfficeDev/microsoft-teams-apps-speaker-queue#6]
I tried all the steps in order, After creating a meeting invite, I tried to add the app. Speaker Queue app was listed .When I choose I got an error saying App doesnt exist or you do not have permission. But i am the admin of this account.

![testSpeaker](https://user-images.githubusercontent.com/72759810/129906646-2df0baec-237b-4ebf-98c9-140b48cc156f.png)

**Comment by cristianoag** [comment]
Please follow those steps:

1.	Open teams, then click Power Apps.
2.	Now click on Build on the top of the screen or on See more just below the Recent apps box.
3.	On the left side, select the Teams team where the Speaker Queue application was installed.
4.	Click on Speaker Queue app to open it in edit mode
5.	Now you will see a button named Publish to Teams on the top right corner of the screen. Click it. 
6.	On the Publish window, click Next.
7.	Now you will see all the channels for the team where you installed the Speaker Queue app.
8.	Just select one of the channels and click + on the right side of the channel name. You will install the app in one tab just to publish the application. Later we can remove the tab. 
9.	Click Save and close. 
10.	Go to the channel where you installed the app and check if a new tab was created with the Speaker Queue app. Click it to test. You will receive a message saying the app needs to run inside a invite.
11.	Now you can go to the invite, edit and add the Speaker Queue application.

**Comment by cristianoag** [comment]
Documentation fixed. Closing the issue.
