### ISSUE TITLE
App fails to load in Teams

### ISSUE THREAD

**Issue by srgopal** [OfficeDev/microsoft-teams-apps-speaker-queue#8]
Hi, I'm getting the below error when trying to add Speaker Queue as a tab in meetings.
![image](https://user-images.githubusercontent.com/48860647/138201299-a0b0b7f1-1ac9-4bd6-ac41-8f5fa9e4cb69.png)

In order to understand the error, i tried accessing the app from browser as well and below is the error I see.
![image](https://user-images.githubusercontent.com/48860647/138202220-43576a47-f79f-4ba5-87a1-ea4ca0b3cf12.png)

FYI, my previous install which was working well months back, started showing the same error, I therefore did a fresh install and get the same error.

Any help would be apprecaited.

**Comment by cristianoag** [comment]
Engineering introduced a step that needs to be completed before using the app. You basically need to publish it to Teams before. I'll update instructions soon. Please follow the steps below:

1.	Open teams, then click Power Apps.
2.	Now click on Build on the top of the screen or on See more just below the Recent apps box.
3.	On the left side, select the Teams team where the Speaker Queue application was installed.
4.	Click on Speaker Queue app to open it in edit mode
5.	Now you will see a button named Publish to Teams on the top right corner of the screen. Click it. 
6.	On the Publish window, click Next.
7.	Now you will see all the channels for the team where you installed the Speaker Queue app.
8.	Just select one of the channels and click + on the right side of the channel name. You will install the app in one tab just to publish the application. 
9.	Click Save and close. 
10.	Go to the channel where you installed the app and check if a new tab was created with the Speaker Queue app. Click it to test. You will receive a message saying the app needs to run inside a invite.
11.	Now you can go to the invite, edit and add the Speaker Queue application.
